# Generated by Django 4.2.7 on 2023-12-20 22:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='501', max_length=1000, verbose_name='Номер')),
                ('number', models.CharField(max_length=1000, verbose_name='Номер')),
                ('price', models.FloatField(default=5000.0, verbose_name='Цена')),
                ('info', models.TextField(max_length=250, null=True, verbose_name='Информация')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('corpus', models.TextField(max_length=20, verbose_name='Корпус')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Номер аудитории', verbose_name='Номер')),
                ('description', models.TextField(blank=True, default='Описание аудитории', null=True, verbose_name='Описание')),
                ('free_audiences', models.IntegerField(blank=True, choices=[(0, 'Свободная'), (1, 'Занята')], null=True, verbose_name='Свободна ли аудитория')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, max_length=100, verbose_name='Статус')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 20, 22, 56, 44, 353639, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Заявка бронирования',
                'verbose_name_plural': 'Заявки бронирования',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookingAudiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_booking', models.DateTimeField(blank=True, null=True, verbose_name='Время бронирования')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.audiences')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.booking')),
            ],
            options={
                'verbose_name': 'Аудитория-Бронирование',
                'verbose_name_plural': 'Аудитории-Бронирование',
                'managed': True,
            },
        ),
    ]
