# Generated by Django 4.2.7 on 2023-12-20 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 22, 58, 41, 395488, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
