# Generated by Django 4.2.7 on 2023-12-20 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 23, 13, 14, 62204, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
